name: CI

on: [ push ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: DeterminateSystems/nix-installer-action@v5
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix flake check
      - run: nix build --print-build-logs .#helloWorld
      - run: nix build --print-build-logs .#springBoot