name: CI

on: [ push ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.0
      - uses: DeterminateSystems/nix-installer-action@v16
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - run: nix flake check
      - run: nix build --print-build-logs .#helloWorld
      - run: nix build --print-build-logs .#springBoot
      - run: nix build --print-build-logs .#funkyDependencies