name: CI

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: DeterminateSystems/nix-installer-action@v2
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix flake check
      - run: nix build .#helloWorld
      - run: nix build .#springBoot